name: Test module

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.runtime.platform }}
    strategy:
      max-parallel: 4
      matrix:
        runtime:
          - python: '3.6'
            platform: 'ubuntu-20.04'
          - python: '3.7'
            platform: 'ubuntu-latest'
          - python: '3.8'
            platform: 'ubuntu-latest'
          - python: '3.9'
            platform: 'ubuntu-latest'
          - python: '3.10'
            platform: 'ubuntu-latest'
          - python: '3.11'
            platform: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.runtime.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 wheel

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Build
      run: |
        python setup.py sdist bdist_wheel

    - name: Install
      run: |
        pip install .

    - name: Test with pytest
      run: |
        pytest
